# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Project site template
# Project
acronym: PST
acronym_lower: pst
version: v0.1.0
description: >- # this means to ignore newlines until the next parameter
  PST is a site template for projects that uses Jekyll and Bootstrap, and can be hosted on GitHub pages.
footer_description: >-
  This project is licensed under the MIT License - see the project <a href="https://github.com/mdmfernandes/project-site-template/blob/master/LICENSE" target="_blank">LICENSE</a> file for details. You are welcome to redistribute it under the license conditions.

# Author
author: Miguel Fernandes
author_email: projects@mdmfernandes.com
author_website: http://mdmfernandes.com
author_projects: https://github.com/mdmfernandes

# Site
baseurl: "/project-site-template" # the subpath of your site, e.g. /blog
url: "https://mdmfernandes.github.io" # the base hostname & protocol for your site, e.g. http://example.com

header_pages:
  - documentation.md
  - tutorials.md

# Collections
collections:
  tutorials:
    output: true
    #permalink: /tutorials/:path
  documentation:
    output: true
    permalink: /docs/:path

# Social networks
twitter_username: mdmfernandes
github_username:  mdmfernandes
linkedin_username: mdmfernandes
#instagram_username: username

# Build settings
markdown: kramdown

# Show blog excerpts
show_excerpts: false
# Google Analytics
google_analytics: 

